name: 'Kaniko build and push image to container registry'
description: 'Build and push image to container registry (use kaniko-login to auth to registry).'

inputs:
  context:
    description: 'Build directory where the Dockerfile resides'
    required: true
  tag:
    description: 'Tag of the built image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create config.json to auth to container registry
      shell: bash
      run: |
        # Build and push (sub in your image, of course)
        /kaniko/executor --dockerfile="${{ inputs.context }}/Dockerfile" \
          --context="${{ inputs.context }}" \
          --destination="${{ inputs.tag }}" \
          --push-retry 5
